"""
PH510 Assignment 4 - Task 4
Parallel Variational Monte Carlo for two hard-sphere bosons in a 2D harmonic trap.

This script is the MPI-parallel extension of the Task 3 Variational Monte
Carlo (VMC) code. The physical system is unchanged: two identical bosons
confined in a two-dimensional isotropic harmonic trap with hard-sphere
exclusion of diameter a. Configurations with r12 <= a are therefore
forbidden.

The variational trial state is

    Psi_T(R, alpha, beta) = exp[-alpha |R|^2 / 2 + r12 / (1 + beta r12)],

where R = (r1, r2) is the four-dimensional configuration, and
r12 = |r1 - r2|.

Copyright (c) 2026 Jack MacQuarrie

This code is released under the MIT License. See the LICENSE file in the
repository for details.

Python Version: 3.9.21
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from typing import Callable, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import numpy as np
from mpi4py import MPI  # pylint: disable=no-name-in-module
import matplotlib.pyplot as plt  # pylint: disable=wrong-import-position,ungrouped-imports


# ---------------------------------------------------------------------------
# Lightweight containers for run settings and measured observables
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class BosonsConfig:
    """
    Numerical parameters defining a single VMC calculation.

    The defaults are chosen to match the Task 3 serial code so that the
    parallel implementation can be compared directly against the serial
    reference results.
    """

    n_samples: int = 50_000
    n_equilibration: int = 5_000
    decorrelation_steps: int = 5
    proposal_width: float = 0.8
    seed: int = 42
    block_size: int = 100
    hard_sphere_diameter: float = 0.0043


@dataclass(frozen=True)
class BosonsResult:
    """
    Container for the output of one VMC calculation.

    This stores the variational parameters together with the estimated
    energy, variance, statistical uncertainty, acceptance rate, and the
    total number of sampled configurations.
    """

    alpha: float
    beta: float
    energy: float
    variance: float
    std_error: float
    acceptance_rate: float
    n_samples: int


@dataclass(frozen=True)
class TimingResult:
    """
    Wall-clock times for the two parallel stages of the calculation.

    Both values are measured using MPI.Wtime() with an MPI barrier before
    each timed region, so they represent true parallel wall time rather
    than the elapsed time on a single rank.
    """

    scan_time: float
    final_time: float


# ---------------------------------------------------------------------------
# Metropolis sampler acting on the full many-body configuration vector
# ---------------------------------------------------------------------------

# pylint: disable=too-few-public-methods
class MetropolisSamplerND:
    """
    Metropolis sampler for an N-dimensional configuration vector.

    The target distribution is supplied through its logarithm rather than
    through the raw probability density. This is numerically safer when the
    wavefunction amplitude becomes very small.

    Trial moves are generated by displacing each coordinate independently
    with a uniform random number in the interval
    [-proposal_width, +proposal_width].
    """

    def __init__(
        self,
        log_prob_func: Callable[[np.ndarray], float],
        proposal_width: float,
        rng: np.random.Generator,
    ) -> None:
        """
        Initialise the Metropolis sampler.

        Parameters
        ----------
        log_prob_func : callable
            Function returning the logarithm of the unnormalised target
            probability density.
        proposal_width : float
            Half-width of the independent uniform proposal distribution
            applied to each coordinate.
        rng : numpy.random.Generator
            Random number generator used in the Markov chain.
        """
        if proposal_width <= 0.0:
            raise ValueError("proposal_width must be positive.")
        self.log_prob_func = log_prob_func
        self.proposal_width = proposal_width
        self.rng = rng

    def step(
        self,
        position: np.ndarray,
        log_prob_current: float,
    ) -> Tuple[np.ndarray, float, bool]:
        """
        Perform one Metropolis update.

        A trial configuration is proposed by perturbing every coordinate of
        the current many-body configuration. The move is then accepted or
        rejected using the usual Metropolis test based on the ratio of the
        target probabilities.

        Parameters
        ----------
        position : numpy.ndarray
            Current configuration vector.
        log_prob_current : float
            Current value of the log-probability.

        Returns
        -------
        tuple
            Updated configuration, updated log-probability, and a Boolean
            acceptance flag.
        """
        trial = position + self.rng.uniform(
            -self.proposal_width,
            self.proposal_width,
            size=position.shape,
        )
        log_prob_trial = self.log_prob_func(trial)

        if not np.isfinite(log_prob_trial):
            return position, log_prob_current, False

        log_ratio = log_prob_trial - log_prob_current
        if log_ratio >= 0.0 or math.log(self.rng.random()) < log_ratio:
            return trial, log_prob_trial, True

        return position, log_prob_current, False


# ---------------------------------------------------------------------------
# Trial state: sampling density and analytical local energy
# ---------------------------------------------------------------------------

def bosons_log_probability(
    alpha: float,
    beta: float,
    hard_sphere_diameter: float,
) -> Callable[[np.ndarray], float]:
    """
    Construct log P(R) for the Gaussian-Jastrow trial state.

    For the variational ansatz

        Psi_T(R) = exp[-alpha R^2 / 2 + r12 / (1 + beta r12)],

    the Metropolis sampling density is proportional to |Psi_T|^2, so the
    logarithm of the unnormalised probability is

        log P(R) = -alpha R^2 + 2 r12 / (1 + beta r12),

    up to an additive constant. Configurations inside the hard core are
    forbidden and are therefore assigned log P = -inf.

    Parameters
    ----------
    alpha : float
        Gaussian width parameter.
    beta : float
        Jastrow correlation parameter.
    hard_sphere_diameter : float
        Hard-sphere diameter a.

    Returns
    -------
    callable
        Function mapping the configuration vector [x1, y1, x2, y2] to the
        logarithm of the unnormalised sampling density.
    """
    if alpha <= 0.0:
        raise ValueError("alpha must be positive.")
    if beta <= 0.0:
        raise ValueError("beta must be positive.")
    if hard_sphere_diameter <= 0.0:
        raise ValueError("hard_sphere_diameter must be positive.")

    def log_prob(r: np.ndarray) -> float:
        """
        Evaluate the unnormalised log-probability at a single configuration.
        """
        dx = r[0] - r[2]
        dy = r[1] - r[3]
        r12 = math.sqrt(dx * dx + dy * dy)

        if r12 <= hard_sphere_diameter:
            return -np.inf

        r_sq = r[0] ** 2 + r[1] ** 2 + r[2] ** 2 + r[3] ** 2
        jastrow = r12 / (1.0 + beta * r12)
        return -alpha * r_sq + 2.0 * jastrow

    return log_prob


def bosons_local_energy(
    alpha: float,
    beta: float,
    hard_sphere_diameter: float,
) -> Callable[[np.ndarray], float]:
    """
    Construct the analytical local energy for the two-boson trial state.

    The local energy is defined by

        E_L(R) = H Psi_T(R) / Psi_T(R),

    where the Hamiltonian contains the kinetic energy of both particles and
    the two-dimensional harmonic confinement V = R^2 / 2 in oscillator
    units. For the present Gaussian-Jastrow ansatz the result can be
    evaluated analytically.

    Parameters
    ----------
    alpha : float
        Gaussian width parameter.
    beta : float
        Jastrow correlation parameter.
    hard_sphere_diameter : float
        Hard-sphere diameter a. Forbidden configurations are assigned an
        infinite local energy, although these should not be sampled by the
        Markov chain.

    Returns
    -------
    callable
        Function mapping the configuration vector [x1, y1, x2, y2] to the
        corresponding local energy.
    """
    if alpha <= 0.0:
        raise ValueError("alpha must be positive.")
    if beta <= 0.0:
        raise ValueError("beta must be positive.")

    def local_energy(r: np.ndarray) -> float:
        """
        Evaluate the local energy for a single many-body configuration.
        """
        dx = r[0] - r[2]
        dy = r[1] - r[3]
        r12 = math.sqrt(dx * dx + dy * dy)

        if r12 <= hard_sphere_diameter:
            return np.inf

        r_sq = r[0] ** 2 + r[1] ** 2 + r[2] ** 2 + r[3] ** 2

        b = 1.0 + beta * r12
        f = 1.0 / (b * b)

        e_onebody = 2.0 * alpha + r_sq * (0.5 - 0.5 * alpha ** 2)
        e_jastrow = alpha * r12 * f - f / r12 + 2.0 * beta * f / b - f * f

        return e_onebody + e_jastrow

    return local_energy


# ---------------------------------------------------------------------------
# Statistical uncertainty estimate for correlated Monte Carlo data
# ---------------------------------------------------------------------------

def blocking_standard_error(
    values: np.ndarray,
    block_size: int,
) -> Tuple[float, int]:
    """
    Estimate the standard error of the mean by block averaging.

    Successive Metropolis samples are correlated, so the naive
    sigma/sqrt(N) estimate can underestimate the true uncertainty. Block
    averaging reduces this problem by replacing the raw Markov chain with a
    shorter sequence of block means that are closer to statistically
    independent.

    Parameters
    ----------
    values : numpy.ndarray
        Sequence of sampled observable values.
    block_size : int
        Number of consecutive samples grouped into one block.

    Returns
    -------
    tuple[float, int]
        Estimated standard error of the mean and the number of complete
        blocks used.
    """
    if block_size < 1:
        raise ValueError("block_size must be at least 1.")
    n_blocks = values.size // block_size
    if n_blocks < 2:
        raise ValueError("Need at least two complete blocks.")
    trimmed = values[: n_blocks * block_size]
    block_means = trimmed.reshape(n_blocks, block_size).mean(axis=1)
    std_error = float(np.sqrt(np.var(block_means, ddof=1) / n_blocks))
    return std_error, n_blocks


# ---------------------------------------------------------------------------
# Core VMC routines
# ---------------------------------------------------------------------------

# pylint: disable=too-many-locals
def _run_vmc_collect(
    config: BosonsConfig,
    alpha: float,
    beta: float,
) -> Tuple[np.ndarray, int, int]:
    """
    Run one VMC calculation and return the raw local-energy samples.

    This helper performs the full Metropolis walk, including equilibration
    and production, and returns the local-energy array together with the
    accepted and attempted move counts. It is used by both the serial
    wrapper and the MPI-parallel final production run.
    """
    a = config.hard_sphere_diameter
    rng = np.random.default_rng(config.seed)

    log_prob_func = bosons_log_probability(alpha, beta, a)
    local_energy_func = bosons_local_energy(alpha, beta, a)

    sampler = MetropolisSamplerND(
        log_prob_func=log_prob_func,
        proposal_width=config.proposal_width,
        rng=rng,
    )

    r0 = 1.0 / math.sqrt(2.0 * alpha)
    position = np.array([r0, 0.0, -r0, 0.0])
    log_prob_current = log_prob_func(position)

    if not np.isfinite(log_prob_current):
        raise ValueError("Initial position has non-finite log probability.")

    for _ in range(config.n_equilibration):
        position, log_prob_current, _ = sampler.step(position, log_prob_current)

    local_energies = np.empty(config.n_samples, dtype=np.float64)
    accepted_moves = 0
    total_moves = 0

    for i in range(config.n_samples):
        for _ in range(config.decorrelation_steps):
            position, log_prob_current, accepted = sampler.step(
                position, log_prob_current
            )
            accepted_moves += int(accepted)
            total_moves += 1
        local_energies[i] = local_energy_func(position)

    return local_energies, accepted_moves, total_moves


def run_bosons_vmc(
    config: BosonsConfig,
    alpha: float,
    beta: float,
) -> BosonsResult:
    """
    Run one serial VMC calculation and return the resulting observables.

    This is the same basic calculation used in Task 3, retained here so
    that each MPI rank can evaluate its assigned parameter points
    independently during the parameter scan.
    """
    if config.n_samples < 2:
        raise ValueError("n_samples must be at least 2.")
    if alpha <= 0.0:
        raise ValueError("alpha must be positive.")
    if beta <= 0.0:
        raise ValueError("beta must be positive.")

    local_energies, accepted_moves, total_moves = _run_vmc_collect(config, alpha, beta)

    energy = float(np.mean(local_energies))
    variance = float(np.var(local_energies, ddof=1))
    std_error, _ = blocking_standard_error(local_energies, config.block_size)
    acceptance_rate = accepted_moves / total_moves if total_moves > 0 else 0.0

    return BosonsResult(
        alpha=alpha,
        beta=beta,
        energy=energy,
        variance=variance,
        std_error=std_error,
        acceptance_rate=acceptance_rate,
        n_samples=config.n_samples,
    )


# ---------------------------------------------------------------------------
# MPI-parallel parameter scan
# ---------------------------------------------------------------------------

def parallel_scan_alpha_beta(
    alpha_values: np.ndarray,
    beta_values: np.ndarray,
    comm: MPI.Comm,
    base_seed: int = 42,
) -> list:
    """
    Distribute the full (alpha, beta) parameter scan across MPI ranks.

    The parameter sweep is embarrassingly parallel: each rank evaluates a
    different subset of grid points independently, and the results are
    gathered only after the local work is complete.

    Rank 0 returns the complete ordered results list. All other ranks
    return an empty list.
    """
    rank = comm.Get_rank()
    size = comm.Get_size()
    n_beta = len(beta_values)

    all_pairs = [
        (
            i,
            j,
            float(alpha_values[i]),
            float(beta_values[j]),
            base_seed + i * n_beta + j,
        )
        for i in range(len(alpha_values))
        for j in range(n_beta)
    ]

    n_total = len(all_pairs)
    block = n_total // size
    remainder = n_total % size
    start = rank * block + min(rank, remainder)
    end = start + block + (1 if rank < remainder else 0)
    local_pairs = all_pairs[start:end]

    local_results = []
    for ai, bj, alpha, beta, seed in local_pairs:
        config = BosonsConfig(
            n_samples=50_000,
            n_equilibration=5_000,
            decorrelation_steps=5,
            proposal_width=0.8 / math.sqrt(alpha),
            seed=seed,
            block_size=100,
        )
        local_results.append((ai * n_beta + bj, run_bosons_vmc(config, alpha, beta)))

    all_gathered = comm.gather(local_results, root=0)

    if rank == 0:
        flat = [item for sublist in all_gathered for item in sublist]
        flat.sort(key=lambda x: x[0])
        return [result for _, result in flat]

    return []


# ---------------------------------------------------------------------------
# MPI-parallel final production run
# ---------------------------------------------------------------------------

def run_parallel_final_vmc(
    alpha: float,
    beta: float,
    n_samples_total: int,
    comm: MPI.Comm,
    base_seed: int = 1729,
) -> Optional[BosonsResult]:
    """
    Run the final high-statistics VMC calculation in parallel.

    Each MPI rank evolves an independent Markov chain at the same
    variational parameters. The local-energy arrays are gathered on rank 0,
    concatenated, and used to evaluate the final mean energy, variance, and
    blocked standard error. The final acceptance rate is computed from the
    total accepted and attempted moves summed across all ranks.

    Parameters
    ----------
    alpha : float
        Best Gaussian variational parameter from the scan.
    beta : float
        Best Jastrow variational parameter from the scan.
    n_samples_total : int
        Total requested number of samples across all ranks.
    comm : MPI.Comm
        MPI communicator.
    base_seed : int, optional
        Base seed for the independent chains. Rank k uses base_seed + k,
        ensuring each chain is uncorrelated.

    Returns
    -------
    BosonsResult or None
        Rank 0 returns the combined result. Other ranks return None.
    """
    rank = comm.Get_rank()
    size = comm.Get_size()

    n_local = n_samples_total // size + (n_samples_total % size if rank == 0 else 0)

    config = BosonsConfig(
        n_samples=n_local,
        n_equilibration=10_000,
        decorrelation_steps=5,
        proposal_width=0.8 / math.sqrt(alpha),
        seed=base_seed + rank,
        block_size=200,
    )

    local_energies, accepted_moves_local, total_moves_local = _run_vmc_collect(
        config, alpha, beta
    )

    all_energies = comm.gather(local_energies, root=0)
    accepted_total = comm.reduce(accepted_moves_local, op=MPI.SUM, root=0)
    moves_total = comm.reduce(total_moves_local, op=MPI.SUM, root=0)

    if rank == 0:
        combined = np.concatenate(all_energies)
        energy = float(np.mean(combined))
        variance = float(np.var(combined, ddof=1))
        std_error, _ = blocking_standard_error(combined, config.block_size)
        acceptance_rate = accepted_total / moves_total if moves_total > 0 else 0.0

        return BosonsResult(
            alpha=alpha,
            beta=beta,
            energy=energy,
            variance=variance,
            std_error=std_error,
            acceptance_rate=float(acceptance_rate),
            n_samples=len(combined),
        )

    return None


# ---------------------------------------------------------------------------
# Rank-0 output and file generation
# ---------------------------------------------------------------------------

def print_summary(results: list, n_procs: int) -> None:
    """
    Print a formatted table of the parallel parameter-scan results.

    The layout is intentionally close to the Task 3 serial output so that
    the parallel and serial calculations can be compared directly.
    """
    best_energy = min(results, key=lambda r: r.energy)
    best_variance = min(results, key=lambda r: r.variance)

    header = (
        f"{'alpha':>8}  {'beta':>8}  {'energy / Ha':>14}  "
        f"{'std err':>12}  {'variance / Ha^2':>18}  {'accept':>8}"
    )
    separator = "-" * len(header)

    print("=" * len(header))
    print(f"PH510 Assignment 4 - Task 4   ({n_procs} MPI ranks)")
    print("Two hard-sphere bosons in a 2D harmonic trap  [parallel]")
    print("=" * len(header))
    print(header)
    print(separator)

    for res in results:
        print(
            f"{res.alpha:8.4f}  {res.beta:8.4f}  {res.energy:14.8f}  "
            f"{res.std_error:12.4e}  {res.variance:18.8e}  "
            f"{res.acceptance_rate:7.2%}"
        )

    print(separator)
    print("Best energy:")
    print(
        f"  alpha = {best_energy.alpha:.4f}, beta = {best_energy.beta:.4f}, "
        f"E = {best_energy.energy:.6f} +/- {best_energy.std_error:.2e} Ha"
    )
    print("Lowest variance:")
    print(
        f"  alpha = {best_variance.alpha:.4f}, beta = {best_variance.beta:.4f}, "
        f"Var = {best_variance.variance:.4e} Ha^2"
    )


def print_final_result(
    result: BosonsResult,
    n_procs: int,
    timing: TimingResult,
) -> None:
    """
    Print the final high-statistics parallel result together with timings.
    """
    print("=" * 60)
    print(f"PH510 Assignment 4 - Task 4  -  Best solution  ({n_procs} ranks)")
    print("=" * 60)
    print(f"alpha            = {result.alpha:.4f}")
    print(f"beta             = {result.beta:.4f}")
    print(f"Energy           = {result.energy:+.6f} Ha")
    print(f"Std. error       = {result.std_error:.2e} Ha")
    print(f"Variance         = {result.variance:.4e} Ha^2")
    print(f"Acceptance rate  = {result.acceptance_rate:.2%}")
    print(f"Samples          = {result.n_samples:,}")
    print(f"Scan wall time   = {timing.scan_time:.6f} s")
    print(f"Final wall time  = {timing.final_time:.6f} s")


def save_results_txt(
    results: list,
    final: BosonsResult,
    n_procs: int,
    timing: TimingResult,
    filename: str = "task4_results.txt",
) -> None:
    """
    Save the scan summary, final production result, and timing information.

    This provides a permanent record of the physical results together with
    the measured runtime of the parallel scan and the final production run.
    """
    best_energy = min(results, key=lambda r: r.energy)
    best_variance = min(results, key=lambda r: r.variance)

    with open(filename, "w", encoding="utf-8") as fout:
        fout.write(f"PH510 Assignment 4 - Task 4  ({n_procs} MPI ranks)\n")
        fout.write("Two hard-sphere bosons in a 2D harmonic trap  [parallel]\n\n")
        fout.write(f"Parameter scan wall time   = {timing.scan_time:.6f} s\n")
        fout.write(f"Final production wall time = {timing.final_time:.6f} s\n\n")
        fout.write(
            f"{'alpha':>8}  {'beta':>8}  {'energy / Ha':>14}  "
            f"{'std err':>12}  {'variance / Ha^2':>18}  {'accept':>8}\n"
        )
        fout.write("-" * 76 + "\n")
        for res in results:
            fout.write(
                f"{res.alpha:8.4f}  {res.beta:8.4f}  {res.energy:14.8f}  "
                f"{res.std_error:12.4e}  {res.variance:18.8e}  "
                f"{res.acceptance_rate:7.2%}\n"
            )
        fout.write("-" * 76 + "\n")
        fout.write(
            f"Best energy:  alpha={best_energy.alpha:.4f}  "
            f"beta={best_energy.beta:.4f}  "
            f"E={best_energy.energy:.6f} +/- {best_energy.std_error:.2e} Ha\n"
        )
        fout.write(
            f"Lowest variance:  alpha={best_variance.alpha:.4f}  "
            f"beta={best_variance.beta:.4f}  "
            f"Var={best_variance.variance:.4e} Ha^2\n\n"
        )
        fout.write("Final high-statistics parallel run:\n")
        fout.write(f"  alpha            = {final.alpha:.4f}\n")
        fout.write(f"  beta             = {final.beta:.4f}\n")
        fout.write(f"  Energy           = {final.energy:+.6f} Ha\n")
        fout.write(f"  Std. error       = {final.std_error:.2e} Ha\n")
        fout.write(f"  Variance         = {final.variance:.4e} Ha^2\n")
        fout.write(f"  Acceptance rate  = {final.acceptance_rate:.2%}\n")
        fout.write(f"  Samples          = {final.n_samples:,}\n")
        fout.write(f"  MPI ranks used   = {n_procs}\n")


def plot_results(
    results: list,
    alpha_values: np.ndarray,
    beta_values: np.ndarray,
    suffix: str = "",
) -> None:
    """
    Plot the energy surface and one-dimensional slices through the minimum.

    The plots are written directly to file rather than displayed
    interactively, which is necessary when running under MPI.
    """
    n_alpha = len(alpha_values)
    n_beta = len(beta_values)
    energy_grid = np.array([r.energy for r in results]).reshape(n_alpha, n_beta)

    best = min(results, key=lambda r: r.energy)
    best_i = int(np.argmin(np.abs(alpha_values - best.alpha)))
    best_j = int(np.argmin(np.abs(beta_values - best.beta)))

    plt.figure(figsize=(8, 6))
    levels = np.linspace(energy_grid.min(), energy_grid.max(), 20)
    cp = plt.contourf(
        beta_values,
        alpha_values,
        energy_grid,
        levels=levels,
        cmap="viridis",
    )
    plt.colorbar(cp, label="Energy / Hartree")
    plt.contour(
        beta_values,
        alpha_values,
        energy_grid,
        levels=levels,
        colors="white",
        alpha=0.3,
    )
    plt.plot(
        best.beta,
        best.alpha,
        "r*",
        markersize=14,
        label=(
            rf"min E = {best.energy:.4f} Ha "
            rf"($\alpha$={best.alpha:.3f}, $\beta$={best.beta:.3f})"
        ),
    )
    plt.xlabel(r"$\beta$")
    plt.ylabel(r"$\alpha$")
    plt.title("Boson VMC energy surface  [parallel Task 4]")
    plt.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(f"task4_energy_surface{suffix}.png", dpi=300)
    plt.close()

    _, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    e_vs_alpha = energy_grid[:, best_j]
    err_vs_alpha = np.array(
        [results[i * n_beta + best_j].std_error for i in range(n_alpha)]
    )
    ax1.errorbar(alpha_values, e_vs_alpha, yerr=err_vs_alpha, fmt="o-", capsize=4)
    ax1.axvline(
        best.alpha,
        color="r",
        linestyle="--",
        label=rf"$\alpha_\mathrm{{opt}}$ = {best.alpha:.3f}",
    )
    ax1.set_xlabel(r"$\alpha$")
    ax1.set_ylabel("Energy / Hartree")
    ax1.set_title(rf"Energy vs $\alpha$  ($\beta$ = {beta_values[best_j]:.3f})")
    ax1.grid(True, linestyle=":")
    ax1.legend()

    e_vs_beta = energy_grid[best_i, :]
    err_vs_beta = np.array(
        [results[best_i * n_beta + j].std_error for j in range(n_beta)]
    )
    ax2.errorbar(beta_values, e_vs_beta, yerr=err_vs_beta, fmt="o-", capsize=4)
    ax2.axvline(
        best.beta,
        color="r",
        linestyle="--",
        label=rf"$\beta_\mathrm{{opt}}$ = {best.beta:.3f}",
    )
    ax2.set_xlabel(r"$\beta$")
    ax2.set_ylabel("Energy / Hartree")
    ax2.set_title(rf"Energy vs $\beta$  ($\alpha$ = {alpha_values[best_i]:.3f})")
    ax2.grid(True, linestyle=":")
    ax2.legend()

    plt.tight_layout()
    plt.savefig(f"task4_energy_slices{suffix}.png", dpi=300)
    plt.close()

