"""
PH510 Assignment 4 - Task 4
Parallel Variational Monte Carlo for two hard-sphere bosons in a 2D harmonic trap.

This script is the MPI-parallel extension of the Task 3 Variational Monte
Carlo (VMC) code. The physical system is unchanged: two identical bosons
confined in a two-dimensional isotropic harmonic trap with hard-sphere
exclusion of diameter a. Configurations with r12 <= a are therefore
forbidden.

The variational trial state is

    Psi_T(R, alpha, beta) = exp[-alpha |R|^2 / 2 + r12 / (1 + beta r12)],

where R = (r1, r2) is the four-dimensional configuration, and
r12 = |r1 - r2|.

Copyright (c) 2026 Jack MacQuarrie

This code is released under the MIT License. See the LICENSE file in the
repository for details.

Python Version: 3.9.21
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from typing import Callable, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import numpy as np
from mpi4py import MPI  # pylint: disable=no-name-in-module
import matplotlib.pyplot as plt  # pylint: disable=wrong-import-position,ungrouped-imports


# ---------------------------------------------------------------------------
# Lightweight containers for run settings and measured observables
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class BosonsConfig:
    """
    Numerical parameters defining a single VMC calculation.

    The defaults are chosen to match the Task 3 serial code so that the
    parallel implementation can be compared directly against the serial
    reference results.
    """

    n_samples: int = 50_000
    n_equilibration: int = 5_000
    decorrelation_steps: int = 5
    proposal_width: float = 0.8
    seed: int = 42
    block_size: int = 100
    hard_sphere_diameter: float = 0.0043


@dataclass(frozen=True)
class BosonsResult:
    """
    Container for the output of one VMC calculation.

    This stores the variational parameters together with the estimated
    energy, variance, statistical uncertainty, acceptance rate, and the
    total number of sampled configurations.
    """

    alpha: float
    beta: float
    energy: float
    variance: float
    std_error: float
    acceptance_rate: float
    n_samples: int


@dataclass(frozen=True)
class TimingResult:
    """
    Wall-clock times for the two parallel stages of the calculation.

    Both values are measured using MPI.Wtime() with an MPI barrier before
    each timed region, so they represent true parallel wall time rather
    than the elapsed time on a single rank.
    """

    scan_time: float
    final_time: float


# ---------------------------------------------------------------------------
# Metropolis sampler acting on the full many-body configuration vector
# ---------------------------------------------------------------------------

# pylint: disable=too-few-public-methods
class MetropolisSamplerND:
    """
    Metropolis sampler for an N-dimensional configuration vector.

    The target distribution is supplied through its logarithm rather than
    through the raw probability density. This is numerically safer when the
    wavefunction amplitude becomes very small.

    Trial moves are generated by displacing each coordinate independently
    with a uniform random number in the interval
    [-proposal_width, +proposal_width].
    """

    def __init__(
        self,
        log_prob_func: Callable[[np.ndarray], float],
        proposal_width: float,
        rng: np.random.Generator,
    ) -> None:
        """
        Initialise the Metropolis sampler.

        Parameters
        ----------
        log_prob_func : callable
            Function returning the logarithm of the unnormalised target
            probability density.
        proposal_width : float
            Half-width of the independent uniform proposal distribution
            applied to each coordinate.
        rng : numpy.random.Generator
            Random number generator used in the Markov chain.
        """
        if proposal_width <= 0.0:
            raise ValueError("proposal_width must be positive.")
        self.log_prob_func = log_prob_func
        self.proposal_width = proposal_width
        self.rng = rng

    def step(
        self,
        position: np.ndarray,
        log_prob_current: float,
    ) -> Tuple[np.ndarray, float, bool]:
        """
        Perform one Metropolis update.

        A trial configuration is proposed by perturbing every coordinate of
        the current many-body configuration. The move is then accepted or
        rejected using the usual Metropolis test based on the ratio of the
        target probabilities.

        Parameters
        ----------
        position : numpy.ndarray
            Current configuration vector.
        log_prob_current : float
            Current value of the log-probability.

        Returns
        -------
        tuple
            Updated configuration, updated log-probability, and a Boolean
            acceptance flag.
        """
        trial = position + self.rng.uniform(
            -self.proposal_width,
            self.proposal_width,
            size=position.shape,
        )
        log_prob_trial = self.log_prob_func(trial)

        if not np.isfinite(log_prob_trial):
            return position, log_prob_current, False

        log_ratio = log_prob_trial - log_prob_current
        if log_ratio >= 0.0 or math.log(self.rng.random()) < log_ratio:
            return trial, log_prob_trial, True

        return position, log_prob_current, False


# ---------------------------------------------------------------------------
# Trial state: sampling density and analytical local energy
# ---------------------------------------------------------------------------

def bosons_log_probability(
    alpha: float,
    beta: float,
    hard_sphere_diameter: float,
) -> Callable[[np.ndarray], float]:
    """
    Construct log P(R) for the Gaussian-Jastrow trial state.

    For the variational ansatz

        Psi_T(R) = exp[-alpha R^2 / 2 + r12 / (1 + beta r12)],

    the Metropolis sampling density is proportional to |Psi_T|^2, so the
    logarithm of the unnormalised probability is

        log P(R) = -alpha R^2 + 2 r12 / (1 + beta r12),

    up to an additive constant. Configurations inside the hard core are
    forbidden and are therefore assigned log P = -inf.

    Parameters
    ----------
    alpha : float
        Gaussian width parameter.
    beta : float
        Jastrow correlation parameter.
    hard_sphere_diameter : float
        Hard-sphere diameter a.

    Returns
    -------
    callable
        Function mapping the configuration vector [x1, y1, x2, y2] to the
        logarithm of the unnormalised sampling density.
    """
    if alpha <= 0.0:
        raise ValueError("alpha must be positive.")
    if beta <= 0.0:
        raise ValueError("beta must be positive.")
    if hard_sphere_diameter <= 0.0:
        raise ValueError("hard_sphere_diameter must be positive.")

    def log_prob(r: np.ndarray) -> float:
        """
        Evaluate the unnormalised log-probability at a single configuration.
        """
        dx = r[0] - r[2]
        dy = r[1] - r[3]
        r12 = math.sqrt(dx * dx + dy * dy)

        if r12 <= hard_sphere_diameter:
            return -np.inf

        r_sq = r[0] ** 2 + r[1] ** 2 + r[2] ** 2 + r[3] ** 2
        jastrow = r12 / (1.0 + beta * r12)
        return -alpha * r_sq + 2.0 * jastrow

    return log_prob


def bosons_local_energy(
    alpha: float,
    beta: float,
    hard_sphere_diameter: float,
) -> Callable[[np.ndarray], float]:
    """
    Construct the analytical local energy for the two-boson trial state.

    The local energy is defined by

        E_L(R) = H Psi_T(R) / Psi_T(R),

    where the Hamiltonian contains the kinetic energy of both particles and
    the two-dimensional harmonic confinement V = R^2 / 2 in oscillator
    units. For the present Gaussian-Jastrow ansatz the result can be
    evaluated analytically.

    Parameters
    ----------
    alpha : float
        Gaussian width parameter.
    beta : float
        Jastrow correlation parameter.
    hard_sphere_diameter : float
        Hard-sphere diameter a. Forbidden configurations are assigned an
        infinite local energy, although these should not be sampled by the
        Markov chain.

    Returns
    -------
    callable
        Function mapping the configuration vector [x1, y1, x2, y2] to the
        corresponding local energy.
    """
    if alpha <= 0.0:
        raise ValueError("alpha must be positive.")
    if beta <= 0.0:
        raise ValueError("beta must be positive.")

    def local_energy(r: np.ndarray) -> float:
        """
        Evaluate the local energy for a single many-body configuration.
        """
        dx = r[0] - r[2]
        dy = r[1] - r[3]
        r12 = math.sqrt(dx * dx + dy * dy)

        if r12 <= hard_sphere_diameter:
            return np.inf

        r_sq = r[0] ** 2 + r[1] ** 2 + r[2] ** 2 + r[3] ** 2

        b = 1.0 + beta * r12
        f = 1.0 / (b * b)

        e_onebody = 2.0 * alpha + r_sq * (0.5 - 0.5 * alpha ** 2)
        e_jastrow = alpha * r12 * f - f / r12 + 2.0 * beta * f / b - f * f

        return e_onebody + e_jastrow

    return local_energy


# ---------------------------------------------------------------------------
# Statistical uncertainty estimate for correlated Monte Carlo data
# ---------------------------------------------------------------------------

def blocking_standard_error(
    values: np.ndarray,
    block_size: int,
) -> Tuple[float, int]:
    """
    Estimate the standard error of the mean by block averaging.

    Successive Metropolis samples are correlated, so the naive
    sigma/sqrt(N) estimate can underestimate the true uncertainty. Block
    averaging reduces this problem by replacing the raw Markov chain with a
    shorter sequence of block means that are closer to statistically
    independent.

    Parameters
    ----------
    values : numpy.ndarray
        Sequence of sampled observable values.
    block_size : int
        Number of consecutive samples grouped into one block.

    Returns
    -------
    tuple[float, int]
        Estimated standard error of the mean and the number of complete
        blocks used.
    """
    if block_size < 1:
        raise ValueError("block_size must be at least 1.")
    n_blocks = values.size // block_size
    if n_blocks < 2:
        raise ValueError("Need at least two complete blocks.")
    trimmed = values[: n_blocks * block_size]
    block_means = trimmed.reshape(n_blocks, block_size).mean(axis=1)
    std_error = float(np.sqrt(np.var(block_means, ddof=1) / n_blocks))
    return std_error, n_blocks


# ---------------------------------------------------------------------------
# Core VMC routines
# ---------------------------------------------------------------------------

# pylint: disable=too-many-locals
def _run_vmc_collect(
    config: BosonsConfig,
    alpha: float,
    beta: float,
) -> Tuple[np.ndarray, int, int]:
    """
    Run one VMC calculation and return the raw local-energy samples.

    This helper performs the full Metropolis walk, including equilibration
    and production, and returns the local-energy array together with the
    accepted and attempted move counts. It is used by both the serial
    wrapper and the MPI-parallel final production run.
    """
    a = config.hard_sphere_diameter
    rng = np.random.default_rng(config.seed)

    log_prob_func = bosons_log_probability(alpha, beta, a)
    local_energy_func = bosons_local_energy(alpha, beta, a)

    sampler = MetropolisSamplerND(
        log_prob_func=log_prob_func,
        proposal_width=config.proposal_width,
        rng=rng,
    )

    r0 = 1.0 / math.sqrt(2.0 * alpha)
    position = np.array([r0, 0.0, -r0, 0.0])
    log_prob_current = log_prob_func(position)

    if not np.isfinite(log_prob_current):
        raise ValueError("Initial position has non-finite log probability.")

    for _ in range(config.n_equilibration):
        position, log_prob_current, _ = sampler.step(position, log_prob_current)

    local_energies = np.empty(config.n_samples, dtype=np.float64)
    accepted_moves = 0
    total_moves = 0

    for i in range(config.n_samples):
        for _ in range(config.decorrelation_steps):
            position, log_prob_current, accepted = sampler.step(
                position, log_prob_current
            )
            accepted_moves += int(accepted)
            total_moves += 1
        local_energies[i] = local_energy_func(position)

    return local_energies, accepted_moves, total_moves


def run_bosons_vmc(
    config: BosonsConfig,
    alpha: float,
    beta: float,
) -> BosonsResult:
    """
    Run one serial VMC calculation and return the resulting observables.

    This is the same basic calculation used in Task 3, retained here so
    that each MPI rank can evaluate its assigned parameter points
    independently during the parameter scan.
    """
    if config.n_samples < 2:
        raise ValueError("n_samples must be at least 2.")
    if alpha <= 0.0:
        raise ValueError("alpha must be positive.")
    if beta <= 0.0:
        raise ValueError("beta must be positive.")

    local_energies, accepted_moves, total_moves = _run_vmc_collect(config, alpha, beta)

    energy = float(np.mean(local_energies))
    variance = float(np.var(local_energies, ddof=1))
    std_error, _ = blocking_standard_error(local_energies, config.block_size)
    acceptance_rate = accepted_moves / total_moves if total_moves > 0 else 0.0

    return BosonsResult(
        alpha=alpha,
        beta=beta,
        energy=energy,
        variance=variance,
        std_error=std_error,
        acceptance_rate=acceptance_rate,
        n_samples=config.n_samples,
    )
