"""
PH510 Assignment 4 - Task 3
Variational Monte Carlo study of two hard-sphere bosons in a 2D harmonic trap.

This script applies the Variational Monte Carlo (VMC) method to estimate
the ground-state energy of two identical bosons confined in a
two-dimensional isotropic harmonic oscillator potential.

Copyright (c) 2026 Jack MacQuarrie

This code is released under the MIT License. See the LICENSE file in the
repository for details.

Python Version: 3.9.21
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Callable, Tuple

import matplotlib.pyplot as plt
import numpy as np


# ---------------------------------------------------------------------------
# Data containers for run parameters and measured observables
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class BosonsConfig:
    """
    Numerical parameters controlling a single VMC run.

    The defaults are chosen to give a reasonable compromise between
    statistical quality and runtime for the two-boson problem.
    """

    n_samples: int = 50_000
    n_equilibration: int = 5_000
    decorrelation_steps: int = 5
    proposal_width: float = 0.8
    seed: int = 42
    block_size: int = 100
    hard_sphere_diameter: float = 0.0043


@dataclass(frozen=True)
class BosonsResult:
    """
    Container for the output of a single VMC calculation.

    This stores the variational parameters together with the estimated
    energy, variance, statistical uncertainty, and Metropolis acceptance
    rate.
    """

    alpha: float
    beta: float
    energy: float
    variance: float
    std_error: float
    acceptance_rate: float
    n_samples: int


# ---------------------------------------------------------------------------
# Metropolis sampler in the full many-body configuration space
# ---------------------------------------------------------------------------

# pylint: disable=too-few-public-methods
class MetropolisSamplerND:
    """
    Simple Metropolis sampler for an N-dimensional configuration vector.

    The target distribution is supplied through its log-probability rather
    than its raw probability density. This avoids unnecessary overflow or
    underflow when the wavefunction amplitude becomes very small.

    Trial moves are generated by independently displacing each coordinate
    with a uniform random number in the interval
    [-proposal_width, +proposal_width].
    """

    def __init__(
        self,
        log_prob_func: Callable[[np.ndarray], float],
        proposal_width: float,
        rng: np.random.Generator,
    ) -> None:
        """
        Initialise the sampler.

        Parameters
        ----------
        log_prob_func : callable
            Function returning the logarithm of the unnormalised target
            probability density.
        proposal_width : float
            Half-width of the uniform proposal distribution applied to each
            coordinate.
        rng : numpy.random.Generator
            Random number generator used for the Metropolis walk.
        """
        if proposal_width <= 0.0:
            raise ValueError("proposal_width must be positive.")
        self.log_prob_func = log_prob_func
        self.proposal_width = proposal_width
        self.rng = rng

    def step(
        self,
        position: np.ndarray,
        log_prob_current: float,
    ) -> Tuple[np.ndarray, float, bool]:
        """
        Perform one Metropolis trial move.

        A candidate configuration is proposed by perturbing every
        coordinate of the current configuration. The move is accepted with
        the usual Metropolis probability based on the ratio of target
        probabilities.

        Parameters
        ----------
        position : numpy.ndarray
            Current configuration vector.
        log_prob_current : float
            Logarithm of the unnormalised probability density at the
            current configuration.

        Returns
        -------
        tuple
            Updated configuration, updated log probability, and a Boolean
            acceptance flag.
        """
        trial = position + self.rng.uniform(
            -self.proposal_width,
            self.proposal_width,
            size=position.shape,
        )
        log_prob_trial = self.log_prob_func(trial)

        if not np.isfinite(log_prob_trial):
            return position, log_prob_current, False

        log_ratio = log_prob_trial - log_prob_current
        if log_ratio >= 0.0 or math.log(self.rng.random()) < log_ratio:
            return trial, log_prob_trial, True

        return position, log_prob_current, False
