"""
PH510 Assignment 4 - Task 3
Variational Monte Carlo study of two hard-sphere bosons in a 2D harmonic trap.

This script applies the Variational Monte Carlo (VMC) method to estimate
the ground-state energy of two identical bosons confined in a
two-dimensional isotropic harmonic oscillator potential.

Copyright (c) 2026 Jack MacQuarrie

This code is released under the MIT License. See the LICENSE file in the
repository for details.

Python Version: 3.9.21
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Callable, Tuple

import matplotlib.pyplot as plt
import numpy as np


# ---------------------------------------------------------------------------
# Data containers for run parameters and measured observables
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class BosonsConfig:
    """
    Numerical parameters controlling a single VMC run.

    The defaults are chosen to give a reasonable compromise between
    statistical quality and runtime for the two-boson problem.
    """

    n_samples: int = 50_000
    n_equilibration: int = 5_000
    decorrelation_steps: int = 5
    proposal_width: float = 0.8
    seed: int = 42
    block_size: int = 100
    hard_sphere_diameter: float = 0.0043


@dataclass(frozen=True)
class BosonsResult:
    """
    Container for the output of a single VMC calculation.

    This stores the variational parameters together with the estimated
    energy, variance, statistical uncertainty, and Metropolis acceptance
    rate.
    """

    alpha: float
    beta: float
    energy: float
    variance: float
    std_error: float
    acceptance_rate: float
    n_samples: int


# ---------------------------------------------------------------------------
# Metropolis sampler in the full many-body configuration space
# ---------------------------------------------------------------------------

# pylint: disable=too-few-public-methods
class MetropolisSamplerND:
    """
    Simple Metropolis sampler for an N-dimensional configuration vector.

    The target distribution is supplied through its log-probability rather
    than its raw probability density. This avoids unnecessary overflow or
    underflow when the wavefunction amplitude becomes very small.

    Trial moves are generated by independently displacing each coordinate
    with a uniform random number in the interval
    [-proposal_width, +proposal_width].
    """

    def __init__(
        self,
        log_prob_func: Callable[[np.ndarray], float],
        proposal_width: float,
        rng: np.random.Generator,
    ) -> None:
        """
        Initialise the sampler.

        Parameters
        ----------
        log_prob_func : callable
            Function returning the logarithm of the unnormalised target
            probability density.
        proposal_width : float
            Half-width of the uniform proposal distribution applied to each
            coordinate.
        rng : numpy.random.Generator
            Random number generator used for the Metropolis walk.
        """
        if proposal_width <= 0.0:
            raise ValueError("proposal_width must be positive.")
        self.log_prob_func = log_prob_func
        self.proposal_width = proposal_width
        self.rng = rng

    def step(
        self,
        position: np.ndarray,
        log_prob_current: float,
    ) -> Tuple[np.ndarray, float, bool]:
        """
        Perform one Metropolis trial move.

        A candidate configuration is proposed by perturbing every
        coordinate of the current configuration. The move is accepted with
        the usual Metropolis probability based on the ratio of target
        probabilities.

        Parameters
        ----------
        position : numpy.ndarray
            Current configuration vector.
        log_prob_current : float
            Logarithm of the unnormalised probability density at the
            current configuration.

        Returns
        -------
        tuple
            Updated configuration, updated log probability, and a Boolean
            acceptance flag.
        """
        trial = position + self.rng.uniform(
            -self.proposal_width,
            self.proposal_width,
            size=position.shape,
        )
        log_prob_trial = self.log_prob_func(trial)

        if not np.isfinite(log_prob_trial):
            return position, log_prob_current, False

        log_ratio = log_prob_trial - log_prob_current
        if log_ratio >= 0.0 or math.log(self.rng.random()) < log_ratio:
            return trial, log_prob_trial, True

        return position, log_prob_current, False


# ---------------------------------------------------------------------------
# Trial state: probability density and analytical local energy
# ---------------------------------------------------------------------------

def bosons_log_probability(
    alpha: float,
    beta: float,
    hard_sphere_diameter: float,
) -> Callable[[np.ndarray], float]:
    """
    Construct log P(R) for the two-boson trial wavefunction.

    For the variational ansatz

        Psi_T(R) = exp[-alpha R^2 / 2 + r12 / (1 + beta r12)],

    the corresponding sampling density is proportional to |Psi_T|^2, so

        log P(R) = -alpha R^2 + 2 r12 / (1 + beta r12),

    up to an additive normalisation constant. Configurations inside the
    hard core, r12 <= a, are forbidden and are therefore assigned
    log P = -inf.

    Parameters
    ----------
    alpha : float
        Gaussian width parameter.
    beta : float
        Jastrow correlation parameter.
    hard_sphere_diameter : float
        Hard-sphere diameter a.

    Returns
    -------
    callable
        Function mapping a configuration vector [x1, y1, x2, y2] to the
        logarithm of the unnormalised sampling density.
    """
    if alpha <= 0.0:
        raise ValueError("alpha must be positive.")
    if beta <= 0.0:
        raise ValueError("beta must be positive.")
    if hard_sphere_diameter <= 0.0:
        raise ValueError("hard_sphere_diameter must be positive.")

    def log_prob(r: np.ndarray) -> float:
        """
        Evaluate the unnormalised log-probability at a given configuration.
        """
        dx = r[0] - r[2]
        dy = r[1] - r[3]
        r12 = math.sqrt(dx * dx + dy * dy)

        if r12 <= hard_sphere_diameter:
            return -np.inf

        r_sq = r[0] ** 2 + r[1] ** 2 + r[2] ** 2 + r[3] ** 2
        jastrow = r12 / (1.0 + beta * r12)
        return -alpha * r_sq + 2.0 * jastrow

    return log_prob


def bosons_local_energy(
    alpha: float,
    beta: float,
    hard_sphere_diameter: float,
) -> Callable[[np.ndarray], float]:
    """
    Construct the analytical local energy for the two-boson trial state.

    The local energy is defined by

        E_L(R) = H Psi_T(R) / Psi_T(R),

    with the Hamiltonian consisting of two 2D kinetic-energy operators and
    a harmonic trapping potential V = R^2 / 2 in oscillator units. For the
    present Gaussian-Jastrow ansatz, the result can be written as

        E_L = 2*alpha + R^2*(1/2 - alpha^2/2)
              + alpha*r12*f - f/r12 + 2*beta*f/b - f^2,

    where
        b = 1 + beta*r12,
        f = 1 / b^2.

    The first term represents the one-body oscillator contribution, while
    the remaining terms arise from the correlation factor.

    Parameters
    ----------
    alpha : float
        Gaussian width parameter.
    beta : float
        Jastrow correlation parameter.
    hard_sphere_diameter : float
        Hard-sphere diameter a. Forbidden configurations are assigned an
        infinite local energy, although these should never be sampled.

    Returns
    -------
    callable
        Function mapping a configuration vector [x1, y1, x2, y2] to the
        corresponding local energy.
    """
    if alpha <= 0.0:
        raise ValueError("alpha must be positive.")
    if beta <= 0.0:
        raise ValueError("beta must be positive.")

    def local_energy(r: np.ndarray) -> float:
        """
        Evaluate the local energy at a given many-body configuration.
        """
        dx = r[0] - r[2]
        dy = r[1] - r[3]
        r12 = math.sqrt(dx * dx + dy * dy)

        if r12 <= hard_sphere_diameter:
            return np.inf

        r_sq = r[0] ** 2 + r[1] ** 2 + r[2] ** 2 + r[3] ** 2

        b = 1.0 + beta * r12
        f = 1.0 / (b * b)

        # Gaussian contribution combined with the harmonic trap.
        e_onebody = 2.0 * alpha + r_sq * (0.5 - 0.5 * alpha ** 2)

        # Correlation correction from the Jastrow factor.
        e_jastrow = alpha * r12 * f - f / r12 + 2.0 * beta * f / b - f * f

        return e_onebody + e_jastrow

    return local_energy

